//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinCurate
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashFlowTTM
    {
        public int Id { get; set; }
        public string ReportDate { get; set; }
        public string PeriodEndingDate { get; set; }
        public string StatementType { get; set; }
        public string CurrencyId { get; set; }
        public int FiscalYearEnd { get; set; }
        public double Amortization { get; set; }
        public double CapitalExpenditure { get; set; }
        public double CashDividendsPaid { get; set; }
        public double CashFlowFromContinuingFinancingActivities { get; set; }
        public double CashFlowFromContinuingInvestingActivities { get; set; }
        public double CashFlowFromContinuingOperatingActivities { get; set; }
        public double FinancingCashFlow { get; set; }
        public double InvestingCashFlow { get; set; }
        public double OperatingCashFlow { get; set; }
        public double BeginningCashPosition { get; set; }
        public double EndCashPosition { get; set; }
        public double ChangesInCash { get; set; }
        public double ChangeInOtherWorkingCapital { get; set; }
        public double ChangeInWorkingCapital { get; set; }
        public double CommonStockDividendPaid { get; set; }
        public double Depreciation { get; set; }
        public double DepreciationAndAmortization { get; set; }
        public double DepreciationAmortizationDepletion { get; set; }
        public double EffectOfExchangeRateChanges { get; set; }
        public double NetCommonStockIssuance { get; set; }
        public double NetIssuancePaymentsOfDebt { get; set; }
        public double NetLongTermDebtIssuance { get; set; }
        public double NetShortTermDebtIssuance { get; set; }
        public double NetIncomeFromContinuingOperations { get; set; }
        public double OperatingGainsLosses { get; set; }
        public double NetOtherFinancingCharges { get; set; }
        public double NetOtherInvestingChanges { get; set; }
        public double CommonStockPayments { get; set; }
        public double LongTermDebtPayments { get; set; }
        public double LongTermDebtIssuance { get; set; }
        public double PurchaseOfIntangibles { get; set; }
        public double PurchaseOfInvestment { get; set; }
        public double PurchaseOfPPE { get; set; }
        public double PurchaseOfBusiness { get; set; }
        public double NetBusinessPurchaseAndSale { get; set; }
        public double NetIntangiblesPurchaseAndSale { get; set; }
        public double NetInvestmentPurchaseAndSale { get; set; }
        public double NetPPEPurchaseAndSale { get; set; }
        public double SaleOfInvestment { get; set; }
        public double SaleOfPPE { get; set; }
        public double StockBasedCompensation { get; set; }
        public double AmortizationOfIntangibles { get; set; }
        public double IssuanceOfDebt { get; set; }
        public double RepaymentOfDebt { get; set; }
        public double RepurchaseOfCapitalStock { get; set; }
        public double FreeCashFlow { get; set; }
        public string FiscalYearChange { get; set; }
        public string FileDate { get; set; }
        public Nullable<double> ChangeInAccountPayable { get; set; }
        public Nullable<double> ChangeInInventory { get; set; }
        public Nullable<double> ChangeInPayable { get; set; }
        public Nullable<double> ChangeInPayablesAndAccruedExpense { get; set; }
        public Nullable<double> ChangeInReceivables { get; set; }
        public Nullable<double> DeferredIncomeTax { get; set; }
        public Nullable<double> DeferredTax { get; set; }
        public Nullable<double> GainLossOnSaleOfBusiness { get; set; }
        public Nullable<double> IncomeTaxPaidSupplementalData { get; set; }
        public Nullable<double> InterestPaidSupplementalData { get; set; }
        public string AccessionNumber { get; set; }
    }
}
