//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinCurate
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyFinancialAvailability
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string ExchangeId { get; set; }
        public byte[] Symbol { get; set; }
        public string CUSIP { get; set; }
        public string CIK { get; set; }
        public string ISIN { get; set; }
        public string SEDOL { get; set; }
        public Nullable<int> Start { get; set; }
        public Nullable<int> End { get; set; }
        public string SectorId { get; set; }
        public byte[] SectorName { get; set; }
        public string IndustryGroupId { get; set; }
        public string IndustryGroupName { get; set; }
        public string IndustryId { get; set; }
        public string IndustryName { get; set; }
        public Nullable<System.DateTime> LatestQuarterlyReportDate { get; set; }
        public Nullable<System.DateTime> LatestAnnualReportDate { get; set; }
        public Nullable<System.DateTime> LatestPreliminaryReportDate { get; set; }
        public Nullable<System.DateTime> LatestSemiAnnualReportDate { get; set; }
    }
}
