//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinCurate
{
    using System;
    using System.Collections.Generic;
    
    public partial class EfficiencyRatio
    {
        public string Symbol { get; set; }
        public string ReportDate { get; set; }
        public string PeriodEndingDate { get; set; }
        public string FileDate { get; set; }
        public string StatementType { get; set; }
        public string DataType { get; set; }
        public string Interim { get; set; }
        public Nullable<int> FiscalYearEnd { get; set; }
        public Nullable<decimal> DaysInSales { get; set; }
        public Nullable<decimal> DaysInInventory { get; set; }
        public Nullable<decimal> DaysInPayment { get; set; }
        public Nullable<decimal> CashConversionCycle { get; set; }
        public Nullable<decimal> ReceivableTurnover { get; set; }
        public Nullable<decimal> InventoryTurnover { get; set; }
        public Nullable<decimal> PayableTurnover { get; set; }
        public Nullable<decimal> FixedAssetsTurnover { get; set; }
        public Nullable<decimal> AssetsTurnover { get; set; }
        public Nullable<decimal> ROE { get; set; }
        public Nullable<decimal> ROA { get; set; }
        public Nullable<decimal> ROIC { get; set; }
        public Nullable<decimal> FCFSalesRatio { get; set; }
        public Nullable<decimal> FCFNetIncomeRatio { get; set; }
        public Nullable<decimal> CapitalExpenditureSalesRatio { get; set; }
        public string AccessionNumber { get; set; }
        public string FormType { get; set; }
        public Nullable<decimal> ROE5YrAvg { get; set; }
        public Nullable<decimal> ROA5YrAvg { get; set; }
        public Nullable<decimal> AVG5YrsROIC { get; set; }
        public Nullable<decimal> NormalizedROIC { get; set; }
        public int Id { get; set; }
    }
}
