//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinCurate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exchanx
    {
        public int Id { get; set; }
        public string ExchangeId { get; set; }
        public string ExchangeName { get; set; }
        public string MIC { get; set; }
        public string RegionId { get; set; }
        public string RegionName { get; set; }
        public string CountryId { get; set; }
        public string CountryName { get; set; }
    }
}
