//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinCurate
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialHealthRatio
    {
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<System.DateTime> PeriodEndingDate { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public string StatementType { get; set; }
        public string DataType { get; set; }
        public string Interim { get; set; }
        public Nullable<int> FiscalYearEnd { get; set; }
        public Nullable<decimal> CurrentRatio { get; set; }
        public Nullable<decimal> QuickRatio { get; set; }
        public Nullable<decimal> DebtTotalCapitalRatio { get; set; }
        public Nullable<decimal> DebtEquityRatio { get; set; }
        public Nullable<decimal> FinancialLeverage { get; set; }
        public Nullable<decimal> TotalDebtToEquity { get; set; }
        public string AccessionNumber { get; set; }
        public string FormType { get; set; }
        public Nullable<decimal> DebttoAssets { get; set; }
        public Nullable<decimal> CommonEquityToAssets { get; set; }
        public string Symbol { get; set; }
        public int Id { get; set; }
    }
}
