//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinCurate
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FincurateEntities : DbContext
    {
        public FincurateEntities()
            : base("name=FincurateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EfficiencyRatio> EfficiencyRatios { get; set; }
        public virtual DbSet<ProfitabilityRatio> ProfitabilityRatios { get; set; }
        public virtual DbSet<EfficiencyRatiosTTM> EfficiencyRatiosTTMs { get; set; }
        public virtual DbSet<PriceStatistic> PriceStatistics { get; set; }
        public virtual DbSet<ProfitabilityRatiosTTM> ProfitabilityRatiosTTMs { get; set; }
        public virtual DbSet<StockPriceAvailability> StockPriceAvailabilities { get; set; }
        public virtual DbSet<ValuationRatio> ValuationRatios { get; set; }
        public virtual DbSet<CompanyFinancialAvailability> CompanyFinancialAvailabilities { get; set; }
        public virtual DbSet<EODHistoricalPriceWithFrequency> EODHistoricalPriceWithFrequencies { get; set; }
        public virtual DbSet<EODPriceHistory> EODPriceHistories { get; set; }
        public virtual DbSet<EODPriceSnapshot> EODPriceSnapshots { get; set; }
        public virtual DbSet<MarketCapitalization> MarketCapitalizations { get; set; }
        public virtual DbSet<PreferredStockYield> PreferredStockYields { get; set; }
        public virtual DbSet<TrailingMarketReturn> TrailingMarketReturns { get; set; }
        public virtual DbSet<ReturnStatistic> ReturnStatistics { get; set; }
        public virtual DbSet<FundHoldingsSummary> FundHoldingsSummaries { get; set; }
        public virtual DbSet<InsiderHoldingsSummary> InsiderHoldingsSummaries { get; set; }
        public virtual DbSet<InstitutionalHoldingsSummary> InstitutionalHoldingsSummaries { get; set; }
        public virtual DbSet<InstitutionalHoldingsSummaryHistory> InstitutionalHoldingsSummaryHistories { get; set; }
        public virtual DbSet<MiscellaneousInfo> MiscellaneousInfos { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<FinancialHealthRatio> FinancialHealthRatios { get; set; }
        public virtual DbSet<IncomeStatement> IncomeStatements { get; set; }
        public virtual DbSet<SharesSnapshot> SharesSnapshots { get; set; }
        public virtual DbSet<Exchanx> Exchanges { get; set; }
        public virtual DbSet<IncomeStatementTTM> IncomeStatementTTMs { get; set; }
        public virtual DbSet<StockExchangeSecurity> StockExchangeSecurities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<InvestmentType> InvestmentTypes { get; set; }
        public virtual DbSet<LanguageCodeList> LanguageCodeLists { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<StockExchangeSecurity1> StockExchangeSecurities1 { get; set; }
        public virtual DbSet<BalanceSheet> BalanceSheets { get; set; }
        public virtual DbSet<CashFlow> CashFlows { get; set; }
        public virtual DbSet<CashFlowsTTM> CashFlowsTTMs { get; set; }
        public virtual DbSet<SharesHistory> SharesHistories { get; set; }
        public virtual DbSet<GrowthRatio> GrowthRatios { get; set; }
    }
}
