//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinCurate
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrowthRatio
    {
        public int Id { get; set; }
        public string Symbol { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<System.DateTime> PeriodEndingDate { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public string StatementType { get; set; }
        public string DataType { get; set; }
        public string Interim { get; set; }
        public Nullable<int> FiscalYearEnd { get; set; }
        public Nullable<decimal> DilutedEPS3MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> DilutedEPS6MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> DilutedEPS9MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> DilutedEPSSequentialGrowth { get; set; }
        public Nullable<decimal> DilutedEPS1YearGrowth { get; set; }
        public Nullable<decimal> DilutedEPS3YearGrowth { get; set; }
        public Nullable<decimal> DilutedEPS5YearGrowth { get; set; }
        public Nullable<decimal> DilutedEPS10YearGrowth { get; set; }
        public Nullable<decimal> DilutedContinuousEPS3MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> DilutedContinuousEPS6MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> DilutedContinuousEPS9MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> DilutedContinuousEPSSequentialGrowth { get; set; }
        public Nullable<decimal> DilutedContinuousEPS1YearGrowth { get; set; }
        public Nullable<decimal> DilutedContinuousEPS3YearGrowth { get; set; }
        public Nullable<decimal> DilutedContinuousEPS5YearGrowth { get; set; }
        public Nullable<decimal> DilutedContinuousEPS10YearGrowth { get; set; }
        public Nullable<decimal> Dividend3MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> Dividend6MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> Dividend9MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> DividendSequentialGrowth { get; set; }
        public Nullable<decimal> Dividend1YearGrowth { get; set; }
        public Nullable<decimal> Dividend3YearGrowth { get; set; }
        public Nullable<decimal> Dividend5YearGrowth { get; set; }
        public Nullable<decimal> Dividend10YearGrowth { get; set; }
        public Nullable<decimal> EquityPerShare3MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> EquityPerShare6MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> EquityPerShare9MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> EquityPerShareSequentialGrowth { get; set; }
        public Nullable<decimal> EquityPerShare1YearGrowth { get; set; }
        public Nullable<decimal> EquityPerShare3YearGrowth { get; set; }
        public Nullable<decimal> EquityPerShare5YearGrowth { get; set; }
        public Nullable<decimal> EquityPerShare10YearGrowth { get; set; }
        public Nullable<decimal> Revenue3MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> Revenue6MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> Revenue9MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> RevenueSequentialGrowth { get; set; }
        public Nullable<decimal> Revenue1YearGrowth { get; set; }
        public Nullable<decimal> Revenue3YearGrowth { get; set; }
        public Nullable<decimal> Revenue5YearGrowth { get; set; }
        public Nullable<decimal> Revenue10YearGrowth { get; set; }
        public Nullable<decimal> OperatingIncome3MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> OperatingIncome6MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> OperatingIncome9MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> OperatingIncomeSequentialGrowth { get; set; }
        public Nullable<decimal> OperatingIncome1YearGrowth { get; set; }
        public Nullable<decimal> OperatingIncome3YearGrowth { get; set; }
        public Nullable<decimal> OperatingIncome5YearGrowth { get; set; }
        public Nullable<decimal> OperatingIncome10YearGrowth { get; set; }
        public Nullable<decimal> NetIncome3MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> NetIncome6MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> NetIncome9MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> NetIncomeSequentialGrowth { get; set; }
        public Nullable<decimal> NetIncome1YearGrowth { get; set; }
        public Nullable<decimal> NetIncome3YearGrowth { get; set; }
        public Nullable<decimal> NetIncome5YearGrowth { get; set; }
        public Nullable<decimal> NetIncome10YearGrowth { get; set; }
        public Nullable<decimal> NetIncomeContOps3MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> NetIncomeContOps6MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> NetIncomeContOps9MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> NetIncomeContOpsSequentialGrowth { get; set; }
        public Nullable<decimal> NetIncomeContOps1YearGrowth { get; set; }
        public Nullable<decimal> NetIncomeContOps3YearGrowth { get; set; }
        public Nullable<decimal> NetIncomeContOps5YearGrowth { get; set; }
        public Nullable<decimal> NetIncomeContOps10YearGrowth { get; set; }
        public Nullable<decimal> CFO3MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> CFO6MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> CFO9MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> CFOSequentialGrowth { get; set; }
        public Nullable<decimal> CFO1YearGrowth { get; set; }
        public Nullable<decimal> CFO3YearGrowth { get; set; }
        public Nullable<decimal> CFO5YearGrowth { get; set; }
        public Nullable<decimal> CFO10YearGrowth { get; set; }
        public Nullable<decimal> FCF3MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> FCF6MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> FCF9MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> FCFSequentialGrowth { get; set; }
        public Nullable<decimal> FCF1YearGrowth { get; set; }
        public Nullable<decimal> FCF3YearGrowth { get; set; }
        public Nullable<decimal> FCF5YearGrowth { get; set; }
        public Nullable<decimal> FCF10YearGrowth { get; set; }
        public Nullable<decimal> OperatingRevenue3MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> OperatingRevenue6MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> OperatingRevenue9MonthSamePeriodGrowth { get; set; }
        public Nullable<decimal> OperatingRevenueSequentialGrowth { get; set; }
        public Nullable<decimal> OperatingRevenue1YearGrowth { get; set; }
        public Nullable<decimal> OperatingRevenue3YearGrowth { get; set; }
        public Nullable<decimal> OperatingRevenue5YearGrowth { get; set; }
        public Nullable<decimal> OperatingRevenue10YearGrowth { get; set; }
        public Nullable<decimal> GrowthAnnCapitalSpending5Year { get; set; }
        public Nullable<decimal> GrowthAnnGrossProfit5Year { get; set; }
        public Nullable<decimal> AvgGrossMargin5Year { get; set; }
        public Nullable<decimal> AvgPostTaxMargin5Year { get; set; }
        public Nullable<decimal> AvgPreTaxMargin5Year { get; set; }
        public Nullable<decimal> AvgNetProfitMargin5Year { get; set; }
        public Nullable<decimal> AvgRetCommonEquity5Year { get; set; }
        public Nullable<decimal> AvgRetAssets5Year { get; set; }
        public Nullable<decimal> AvgRetInvestedCapital5Year { get; set; }
        public string AccessionNumber { get; set; }
        public string FormType { get; set; }
        public Nullable<decimal> RegressionGrowthOperatingRevenue5Years { get; set; }
        public Nullable<decimal> NormalizedDilutedEPSGrowth1year { get; set; }
        public Nullable<decimal> NormalizedDilutedEPSGrowth3year { get; set; }
        public Nullable<decimal> NormalizedDilutedEPSGrowth5year { get; set; }
        public Nullable<decimal> NormalizedDilutedEPSGrowth10year { get; set; }
        public Nullable<decimal> NormalizedDilutedEPSSamePeriodGrowth3months { get; set; }
        public Nullable<decimal> NormalizedDilutedEPSSamePeriodGrowth6months { get; set; }
        public Nullable<decimal> NormalizedDilutedEPSSamePeriodGrowth9months { get; set; }
        public Nullable<decimal> NormalizedDilutedEPSSequentialGrowth { get; set; }
        public Nullable<decimal> NormalizedBasicEPSGrowth1year { get; set; }
        public Nullable<decimal> NormalizedBasicEPSGrowth3year { get; set; }
        public Nullable<decimal> NormalizedBasicEPSGrowth5year { get; set; }
        public Nullable<decimal> NormalizedBasicEPSGrowth10year { get; set; }
        public Nullable<decimal> NormalizedBasicEPSSamePeriodGrowth3months { get; set; }
        public Nullable<decimal> NormalizedBasicEPSSamePeriodGrowth6months { get; set; }
        public Nullable<decimal> NormalizedBasicEPSSamePeriodGrowth9months { get; set; }
        public Nullable<decimal> NormalizedBasicEPSSequentialGrowth { get; set; }
    }
}
