//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinCurate
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestmentType
    {
        public int Id { get; set; }
        public string InvestmentTypeId { get; set; }
        public string InvestmentTypeName { get; set; }
    }
}
