//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinCurate
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketCapitalization
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> MarketCapDate { get; set; }
        public Nullable<decimal> MarketCap { get; set; }
        public Nullable<decimal> EnterpriseValue { get; set; }
        public string CurrencyId { get; set; }
        public Nullable<decimal> SharesOutstanding { get; set; }
        public Nullable<System.DateTime> SharesDate { get; set; }
        public string Symbol { get; set; }
    }
}
