//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinCurate
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceStatistic
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> AsOfDate { get; set; }
        public Nullable<decimal> DayHigh52Week { get; set; }
        public Nullable<System.DateTime> HighDate52Week { get; set; }
        public Nullable<decimal> DayLow52Week { get; set; }
        public Nullable<System.DateTime> LowDate52Week { get; set; }
        public Nullable<decimal> AverageVolumeYearly { get; set; }
        public Nullable<decimal> TotalVolume { get; set; }
        public Nullable<decimal> VolumeAvgDay13Week { get; set; }
    }
}
