//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinCurate
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharesSnapshot
    {
        public string Symbol { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> TSODate { get; set; }
        public Nullable<decimal> CompanyTSO { get; set; }
        public string ShareLevelTSOSource { get; set; }
        public Nullable<decimal> ShareLevelTSO { get; set; }
        public Nullable<decimal> QuotedTSO { get; set; }
        public Nullable<decimal> UnquotedTSO { get; set; }
        public Nullable<System.DateTime> FloatDate { get; set; }
        public Nullable<decimal> FloatShare { get; set; }
        public Nullable<decimal> InsiderHolding { get; set; }
        public Nullable<decimal> FloatShareToTotalSharesOutstanding { get; set; }
        public Nullable<System.DateTime> BalanceSheetDate { get; set; }
        public Nullable<decimal> ShareClassLevelTreasuryShareOutstanding { get; set; }
        public Nullable<decimal> SharesOutstandingWithBalanceSheetEndingDate { get; set; }
    }
}
