//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinCurate
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharesHistory
    {
        public int Id { get; set; }
        public string Symbol { get; set; }
        public Nullable<System.DateTime> TSODate { get; set; }
        public string CompanyTSO { get; set; }
        public string ShareLevelTSOSource { get; set; }
        public string ShareLevelTSO { get; set; }
        public string QuotedTSO { get; set; }
        public string UnquotedTSO { get; set; }
        public Nullable<System.DateTime> FloatDate { get; set; }
        public string FloatShare { get; set; }
        public string InsiderHolding { get; set; }
        public string FloatShareToTotalSharesOutstanding { get; set; }
        public string ReasonOfShareChange { get; set; }
        public Nullable<System.DateTime> BalanceSheetDate { get; set; }
        public string ShareClassLevelTreasuryShareOutstanding { get; set; }
        public string SharesOutstandingWithBalanceSheetEndingDate { get; set; }
        public string ShareClassLevelTreasuryShareOutstandingFromCover { get; set; }
        public string ShareClassLevelTreasuryShareOutstandingFromInterim { get; set; }
        public string ShareClassLevelTreasuryShareOutstandingFromOther { get; set; }
    }
}
