//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinCurate
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrailingMarketReturn
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> AsOfDate { get; set; }
        public Nullable<decimal> Return1D { get; set; }
        public Nullable<decimal> Return1W { get; set; }
        public Nullable<decimal> Return1M { get; set; }
        public Nullable<decimal> Return3M { get; set; }
        public Nullable<decimal> Return6M { get; set; }
        public Nullable<decimal> Return9M { get; set; }
        public Nullable<decimal> Return1Y { get; set; }
        public Nullable<decimal> Return3Y { get; set; }
        public Nullable<decimal> Return5Y { get; set; }
        public Nullable<decimal> Return7Y { get; set; }
        public Nullable<decimal> Return10Y { get; set; }
        public Nullable<decimal> ReturnMTD { get; set; }
        public Nullable<decimal> ReturnQTD { get; set; }
        public Nullable<decimal> ReturnYTD { get; set; }
    }
}
