//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinCurate
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValuationRatio
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> AsOfDate { get; set; }
        public Nullable<decimal> SalesPerShare { get; set; }
        public Nullable<decimal> GrowthAnnSalesPerShare5Year { get; set; }
        public Nullable<decimal> BookValuePerShare { get; set; }
        public Nullable<decimal> CFPerShare { get; set; }
        public Nullable<decimal> FCFPerShare { get; set; }
        public Nullable<decimal> PriceToEPS { get; set; }
        public Nullable<decimal> RatioPE5YearHigh { get; set; }
        public Nullable<decimal> RatioPE5YearLow { get; set; }
        public Nullable<decimal> PriceToBook { get; set; }
        public Nullable<decimal> PriceToSales { get; set; }
        public Nullable<decimal> PriceToCashFlow { get; set; }
        public Nullable<decimal> PriceToFreeCashFlow { get; set; }
        public Nullable<decimal> DivRate { get; set; }
        public Nullable<decimal> DividendYield { get; set; }
        public Nullable<decimal> DivPayoutTotOps { get; set; }
        public Nullable<decimal> DivPayout5Year { get; set; }
        public Nullable<decimal> DivYield5Year { get; set; }
        public Nullable<decimal> PayoutRatio { get; set; }
        public Nullable<decimal> SustainableGrowthRate { get; set; }
        public Nullable<decimal> CashReturn { get; set; }
        public Nullable<decimal> ForwardEarningYield { get; set; }
        public Nullable<decimal> PEGRatio { get; set; }
        public Nullable<decimal> PEGPayback { get; set; }
        public Nullable<decimal> ForwardDividendYield { get; set; }
        public Nullable<decimal> ForwardPERatio { get; set; }
        public Nullable<decimal> TangibleBookValuePerShare { get; set; }
        public Nullable<decimal> TangibleBVPerShare3YrAvg { get; set; }
        public Nullable<decimal> TangibleBVPerShare5YrAvg { get; set; }
        public Nullable<decimal> EVToEBITDA { get; set; }
        public Nullable<decimal> RatioPE5YearAverage { get; set; }
        public Nullable<decimal> NormalizedPERatio { get; set; }
        public Nullable<decimal> FCFYield { get; set; }
        public Nullable<decimal> EVToForwardEBIT { get; set; }
        public Nullable<decimal> EVToForwardEBITDA { get; set; }
        public Nullable<decimal> EVToForwardRevenue { get; set; }
        public Nullable<decimal> TwoYearsEVToForwardEBIT { get; set; }
        public Nullable<decimal> TwoYearsEVToForwardEBITDA { get; set; }
        public Nullable<decimal> FirstYearEstimatedEPSGrowth { get; set; }
        public Nullable<decimal> SecondYearEstimatedEPSGrowth { get; set; }
        public Nullable<decimal> NormalizedPEG { get; set; }
        public string Symbol { get; set; }
    }
}
