using System;
using System.Collections.Generic;
using System.Text;

namespace CommonLibrary.Models
{
    public class BalanceSheetEntityList
    {
        public string ReportDate { get; set; }
        public string PeriodEndingDate { get; set; }
        public string FileDate { get; set; }
        public string StatementType { get; set; }
        public string DataType { get; set; }
        public string Interim { get; set; }
        public string CurrencyId { get; set; }
        public int FiscalYearEnd { get; set; }
        public double AccountsPayable { get; set; }
        public double AccountsReceivable { get; set; }
        public double GrossAccountsReceivable { get; set; }
        public double NonCurrentAccountsReceivable { get; set; }
        public double AccumulatedDepreciation { get; set; }
        public double GainsLossesNotAffectingRetainedEarnings { get; set; }
        public double AllowanceForDoubtfulAccountsReceivable { get; set; }
        public double CapitalStock { get; set; }
        public double CashAndCashEquivalents { get; set; }
        public double CashCashEquivalentsAndShortTermInvestments { get; set; }
        public double CommonStock { get; set; }
        public double CommonStockEquity { get; set; }
        public double CurrentAssets { get; set; }
        public double CurrentDebt { get; set; }
        public double CurrentDebtAndCapitalLeaseObligation { get; set; }
        public double CurrentLiabilities { get; set; }
        public double NonCurrentDeferredLiabilities { get; set; }
        public double CurrentDeferredLiabilities { get; set; }
        public double CurrentDeferredRevenue { get; set; }
        public double NonCurrentDeferredRevenue { get; set; }
        public double NonCurrentDeferredTaxesAssets { get; set; }
        public double DefinedPensionBenefit { get; set; }
        public double EmployeeBenefits { get; set; }
        public double FinishedGoods { get; set; }
        public double Goodwill { get; set; }
        public double GoodwillAndOtherIntangibleAssets { get; set; }
        public double GrossPPE { get; set; }
        public double Inventory { get; set; }
        public double InvestmentsAndAdvances { get; set; }
        public double LongTermDebt { get; set; }
        public double LongTermDebtAndCapitalLeaseObligation { get; set; }
        public double MinorityInterest { get; set; }
        public double NetPPE { get; set; }
        public double OtherCurrentAssets { get; set; }
        public double OtherCurrentLiabilities { get; set; }
        public double OtherIntangibleAssets { get; set; }
        public double OtherReceivables { get; set; }
        public double ShortTermInvestments { get; set; }
        public double Payables { get; set; }
        public double PayablesAndAccruedExpenses { get; set; }
        public double NonCurrentPensionAndOtherPostretirementBenefitPlans { get; set; }
        public double PrepaidAssets { get; set; }
        public double Receivables { get; set; }
        public double RecievablesAdjustmentsAllowances { get; set; }
        public double RestrictedCash { get; set; }
        public double RetainedEarnings { get; set; }
        public double StockholdersEquity { get; set; }
        public double TotalTaxPayable { get; set; }
        public double TotalAssets { get; set; }
        public double TotalCapitalization { get; set; }
        public double TotalNonCurrentAssets { get; set; }
        public double TreasuryStock { get; set; }
        public double WorkInProcess { get; set; }
        public double OtherNonCurrentLiabilities { get; set; }
        public double InvestedCapital { get; set; }
        public double TangibleBookValue { get; set; }
        public double TotalEquity { get; set; }
        public double WorkingCapital { get; set; }
        public double TotalDebt { get; set; }
        public double CurrentDeferredAssets { get; set; }
        public double NonCurrentDeferredAssets { get; set; }
        public double OrdinarySharesNumber { get; set; }
        public double TreasurySharesNumber { get; set; }
        public double TotalLiabilitiesNetMinorityInterest { get; set; }
        public double TotalNonCurrentLiabilitiesNetMinorityInterest { get; set; }
        public double TotalEquityGrossMinorityInterest { get; set; }
        public string AccessionNumber { get; set; }
        public string FormType { get; set; }
        public double NetTangibleAssets { get; set; }
        public double PensionandOtherPostRetirementBenefitPlansCurrent { get; set; }
        public double OtherInvestments { get; set; }
        public string FiscalYearChange { get; set; }

        public int Id { get; set; }
        public string NonCurrentAccruedExpenses { get; set; }
        public string BuildingsAndImprovements { get; set; }
        public string CommercialPaper { get; set; }
        public string NonCurrentDeferredTaxesLiabilities { get; set; }
        public string DerivativeProductLiabilities { get; set; }
        public string FinancialAssets { get; set; }
        public string LandAndImprovements { get; set; }
        public string LoansReceivable { get; set; }
        public string LongTermEquityInvestment { get; set; }
        public string MachineryFurnitureEquipment { get; set; }
        public string NonCurrentNoteReceivables { get; set; }
        public string OtherNonCurrentAssets { get; set; }
        public string OtherProperties { get; set; }
        public string NonCurrentPrepaidAssets { get; set; }
        public string Properties { get; set; }
        public string LongTermProvisions { get; set; }
        public string InvestmentsinAssociatesatCost { get; set; }
        public string OtherEquityInterest { get; set; }
        public string TradeandOtherPayablesNonCurrent { get; set; }
        public string CurrentAccruedExpenses { get; set; }
        public string AccruedInterestReceivable { get; set; }
        public string AccruedInvestmentIncome { get; set; }
        public string AdditionalPaidInCapital { get; set; }
        public string AdvanceFromFederalHomeLoanBanks { get; set; }
        public string AllowanceForLoansAndLeaseLosses { get; set; }
        public string AllowanceForNotesReceivable { get; set; }
        public string AssetsHeldForSale { get; set; }
        public string AssetsOfDiscontinuedOperations { get; set; }
        public string AvailableForSaleSecurities { get; set; }
        public string BankAcceptanceExecutedAndOutstanding { get; set; }
        public string BankIndebtedness { get; set; }
        public string BankLoan { get; set; }
        public string BankOwnedLifeInsurance { get; set; }
        public string SecurityBorrowed { get; set; }
        public string Cash { get; set; }
        public string CashEquivalents { get; set; }
        public string CashAndDueFromBanks { get; set; }
        public string CashCashEquivalentsAndFederalFundsSold { get; set; }
        public string CasualtyClaims { get; set; }
        public string CededUnearnedPremiums { get; set; }
        public string CommercialLoan { get; set; }
        public string CommonStocksAvailableForSale { get; set; }
        public string ConstructionInProgress { get; set; }
        public string ConsumerLoan { get; set; }
        public string MinimumPensionLiabilities { get; set; }
        public string CurrentCapitalLeaseObligation { get; set; }
        public string CustomerAcceptances { get; set; }
        public string DeferredAcquisitionCosts { get; set; }
        public string DeferredAssets { get; set; }
        public string DeferredCosts { get; set; }
        public string DeferredFinancingCosts { get; set; }
        public string DeferredPolicyAcquisitionCosts { get; set; }
        public string DeferredTaxAssets { get; set; }
        public string CurrentDeferredTaxesAssets { get; set; }
        public string CurrentDeferredTaxesLiabilities { get; set; }
        public string DerivativeAssets { get; set; }
        public string DividendsPayable { get; set; }
        public string ESOPDebtGuarantee { get; set; }
        public string EquityInvestments { get; set; }
        public string FacilitiesAndOther { get; set; }
        public string FederalFundsPurchased { get; set; }
        public string FederalFundsPurchasedAndSecuritiesSoldUnderAgreementToRepurchase { get; set; }
        public string FederalFundsSold { get; set; }
        public string FederalFundsSoldAndSecuritiesPurchaseUnderAgreementsToResell { get; set; }
        public string FederalHomeLoanBankStock { get; set; }
        public string FinancialInstrumentsSoldUnderAgreementsToRepurchase { get; set; }
        public string FixedMaturitiesAvailableForSale { get; set; }
        public string FixedMaturitiesHeldToMaturity { get; set; }
        public string FixedMaturitiesTrading { get; set; }
        public string FixedMaturityInvestments { get; set; }
        public string FlightFleetVehicleAndRelatedEquipments { get; set; }
        public string ForeclosedAssets { get; set; }
        public string ForeignComponent { get; set; }
        public string ForeignCurrencyTranslationAdjustments { get; set; }
        public string FuelAndNaturalGas { get; set; }
        public string FuturePolicyBenefits { get; set; }
        public string GeneralPartnershipCapital { get; set; }
        public string GrossLoan { get; set; }
        public string GuaranteedInvestmentContract { get; set; }
        public string HeldToMaturitySecurities { get; set; }
        public string IncomeTaxPayable { get; set; }
        public string InterestBearingDepositsLiabilities { get; set; }
        public string InterestPayable { get; set; }
        public string InterestBearingDepositsAssets { get; set; }
        public string InventoriesAdjustmentsAllowances { get; set; }
        public string InvestmentTaxCredits { get; set; }
        public string InvestmentsInAffiliatesSubsidiariesAssociatesAndJointVentures { get; set; }
        public string InvestmentsInOtherVenturesUnderEquityMethod { get; set; }
        public string InvestmentsInVariableInterestEntity { get; set; }
        public string Leases { get; set; }
        public string LiabilitiesOfDiscontinuedOperations { get; set; }
        public string LimitedPartnershipCapital { get; set; }
        public string LimitedPartnership { get; set; }
        public string LineOfCredit { get; set; }
        public string LoansHeldForSale { get; set; }
        public string LongTermCapitalLeaseObligation { get; set; }
        public string MaterialsAndSupplies { get; set; }
        public string MineralProperties { get; set; }
        public string MoneyMarketInvestments { get; set; }
        public string MortgageLoan { get; set; }
        public string MortgageAndConsumerloans { get; set; }
        public string NaturalResourceAssets { get; set; }
        public string NetLoan { get; set; }
        public string NetOtherUnrealizedGainLoss { get; set; }
        public string NetUnrealizedGainLossForeignCurrency { get; set; }
        public string NetUnrealizedGainLossInvestments { get; set; }
        public string NonInterestBearingDeposits { get; set; }
        public string CurrentNotesPayable { get; set; }
        public string NotesReceivable { get; set; }
        public string GrossNotesReceivable { get; set; }
        public string OtherAssets { get; set; }
        public string OtherCapitalStock { get; set; }
        public string OtherDeferredCosts { get; set; }
        public string OtherDeposits { get; set; }
        public string OtherEquityAdjustments { get; set; }
        public string OtherInterestEarningAssets { get; set; }
        public string OtherInventories { get; set; }
        public string OtherInvestedAssets { get; set; }
        public string OtherRealEstateOwned { get; set; }
        public string Patents { get; set; }
        public string PolicyLoans { get; set; }
        public string TotalPolicyHoldersLiabilities { get; set; }
        public string PolicyholderFunds { get; set; }
        public string PreferredSecuritiesOutsideStockEquity { get; set; }
        public string TrustPreferredSecurities { get; set; }
        public string PreferredStock { get; set; }
        public string PreferredStockEquity { get; set; }
        public string PreferredStockOfSubsidiary { get; set; }
        public string PreferredStocksAvailableForSale { get; set; }
        public string PremiumsReceivable { get; set; }
        public string PrepaidReinsurancePremiums { get; set; }
        public string CurrentProvisions { get; set; }
        public string PurchasedComponents { get; set; }
        public string RawMaterials { get; set; }
        public string RealEstateHeldForSale { get; set; }
        public string RealEstateAndRealEstateJointVenturesHeldForInvestment { get; set; }
        public string RedeemablePreferredStock { get; set; }
        public string RegulatoryAssets { get; set; }
        public string RegulatoryLiabilities { get; set; }
        public string ReinsuranceBalancesPayable { get; set; }
        public string ReinsuranceReceivables { get; set; }
        public string ReinsuranceRecoverable { get; set; }
        public string ReinsuranceRecoverableForPaidLosses { get; set; }
        public string ReinsuranceRecoverableForUnpaidLosses { get; set; }
        public string RestrictedCashAndCashEquivalents { get; set; }
        public string RestrictedCashAndInvestments { get; set; }
        public string RestrictedCommonStock { get; set; }
        public string RestrictedInvestments { get; set; }
        public string SecuritiesLendingCollateral { get; set; }
        public string SecuritiesLendingPayable { get; set; }
        public string SecurityAgreeToBeResell { get; set; }
        public string SecuritySoldNotYetRepurchased { get; set; }
        public string SeparateAccountAssets { get; set; }
        public string SeparateAccountLiability { get; set; }
        public string ShortTermInvestmentsAvailableForSale { get; set; }
        public string ShortTermInvestmentsHeldToMaturity { get; set; }
        public string ShortTermInvestmentsTrading { get; set; }
        public string StudentLoan { get; set; }
        public string TaxesReceivable { get; set; }
        public string TimeDepositsPlaced { get; set; }
        public string TotalDeferredCreditsAndOtherNonCurrentLiabilities { get; set; }
        public string TotalDeposits { get; set; }
        public string TotalInvestments { get; set; }
        public string TotalLiabilities { get; set; }
        public string TotalNonCurrentLiabilities { get; set; }
        public string TotalPartnershipCapital { get; set; }
        public string TradingAssets { get; set; }
        public string TradingLiabilities { get; set; }
        public string TradingSecurities { get; set; }
        public string UnbilledReceivables { get; set; }
        public string UnearnedIncome { get; set; }
        public string UnearnedPremiums { get; set; }
        public string UnpaidLossAndLossReserve { get; set; }
        public string UnrealizedGainLoss { get; set; }
        public string CapitalLeaseObligations { get; set; }
        public string OtherLiabilities { get; set; }
        public string OtherPayable { get; set; }
        public string CashValueOfLifeInsurance { get; set; }
        public string CommonUtilityPlant { get; set; }
        public string ElectricUtilityPlant { get; set; }
        public string NaturalGasFuelAndOther { get; set; }
        public string NetUtilityPlant { get; set; }
        public string WaterProduction { get; set; }
        public string SecuritiesAndInvestments { get; set; }
        public string PreferredSharesNumber { get; set; }
        public string TradingAndOtherReceivable { get; set; }
        public string SecuritiesLoaned { get; set; }
        public string ParticipatingPolicyholderEquity { get; set; }
        public string DuefromRelatedPartiesCurrent { get; set; }
        public string DuefromRelatedPartiesNonCurrent { get; set; }
        public string DuetoRelatedParties { get; set; }
        public string DuetoRelatedPartiesCurrent { get; set; }
        public string DuetoRelatedPartiesNonCurrent { get; set; }
        public string NetAssets { get; set; }
        public string InvestmentProperties { get; set; }
        public string InvestmentsinSubsidiariesatCost { get; set; }
        public string InvestmentsinJointVenturesatCost { get; set; }
        public string InvestmentinFinancialAssets { get; set; }
        public string FinanceLeaseReceivables { get; set; }
        public string ConvertibleLoansCurrent { get; set; }
        public string BankLoansCurrent { get; set; }
        public string OtherLoansCurrent { get; set; }
        public string AccruedandDeferredIncome { get; set; }
        public string BankLoansNonCurrent { get; set; }
        public string OtherLoansNonCurrent { get; set; }
        public string OtherReserves { get; set; }
        public string LoansandAdvancestoBank { get; set; }
        public string LoansandAdvancestoCustomer { get; set; }
        public string TreasuryBillsandOtherEligibleBills { get; set; }
        public string EquitySharesInvestments { get; set; }
        public string DepositsbyBank { get; set; }
        public string CustomerAccounts { get; set; }
        public string ItemsinTheCourseofTransmissiontoOtherBanks { get; set; }
        public string TradingandFinancialLiabilities { get; set; }
        public string DebtSecuritiesinIssue { get; set; }
        public string SubordinatedLiabilities { get; set; }
        public string ProvisionsTotal { get; set; }
        public string OperatingLeaseAssets { get; set; }
        public string ClaimsOutstanding { get; set; }
        public string LongTermContracts { get; set; }
        public string RealEstate { get; set; }
        public string PaymentofBills { get; set; }
        public string LiabilitiesHeldforSaleCurrent { get; set; }
        public string LiabilitiesHeldforSaleNonCurrent { get; set; }
        public string UnclassifiedCurrentAssets { get; set; }
        public string DebtSecurities { get; set; }
        public string TotalFinancialLeaseObligations { get; set; }
        public string AccruedandDeferredIncomeCurrent { get; set; }
        public string AccruedandDeferredIncomeNonCurrent { get; set; }
        public string FinanceLeaseReceivablesCurrent { get; set; }
        public string FinanceLeaseReceivablesNonCurrent { get; set; }
        public string FinancialLiabilitiesCurrent { get; set; }
        public string FinancialLiabilitiesNonCurrent { get; set; }
        public string FinancialAssetsDesignatedasFairValueThroughProfitorLossTotal { get; set; }
        public string TaxesAssetsCurrent { get; set; }
        public string InterestBearingBorrowingsNonCurrent { get; set; }
        public string NonInterestBearingBorrowingsNonCurrent { get; set; }
        public string InterestBearingBorrowingsCurrent { get; set; }
        public string NonInterestBearingBorrowingsCurrent { get; set; }
        public string CashandBalanceswithCentralBanks { get; set; }
        public string PlacementwithBanksandOtherFinancialInstitutions { get; set; }
        public string OtherLoanAssets { get; set; }
        public string HedgingAssetsTotal { get; set; }
        public string AssetsPledgedasCollateralSubjecttoSaleorRepledgingTotal { get; set; }
        public string TaxAssetsTotal { get; set; }
        public string AdvancesfromCentralBanks { get; set; }
        public string CertificatesofDepositsandOtherDebtSecuritiesIssued { get; set; }
        public string DepositCertificates { get; set; }
        public string DebenturesandDebtCertificates { get; set; }
        public string InterestBearingBorrowingsTotal { get; set; }
        public string NonInterestBearingBorrowingsTotal { get; set; }
        public string OtherBorrowedFunds { get; set; }
        public string FinancialLiabilitiesDesignatedasFairValueThroughProfitorLossTotal { get; set; }
        public string FinancialLiabilitiesMeasuredatAmortizedCostTotal { get; set; }
        public string LoanCapital { get; set; }
        public string HedgingLiabilitiesTotal { get; set; }
        public string LiabilitiesRecognizedforFairValueChangesinPortfolioHedgeofInterestRateRisk { get; set; }
        public string AccruedLiabilitiesTotal { get; set; }
        public string DeferredIncomeTotal { get; set; }
        public string DeferredTaxLiabilitiesTotal { get; set; }
        public string ReinsuranceAssets { get; set; }
        public string ReinsuranceShareofInsuranceContract { get; set; }
        public string ReinsuranceShareofAccruedPolicyholderClaims { get; set; }
        public string DepositsMadeunderAssumedReinsuranceContract { get; set; }
        public string InsuranceContractAssets { get; set; }
        public string InsuranceReceivables { get; set; }
        public string InsuranceContractLiabilities { get; set; }
        public string InsurancePayables { get; set; }
        public string DepositsReceivedunderCededInsuranceContract { get; set; }
        public string InvestmentContractLiabilities { get; set; }
        public string ConstructionGrants { get; set; }
        public string DeferredCostCurrent { get; set; }
        public string PensionAndOtherPostretirementBenefitPlansTotal { get; set; }
        public string LiabilitiesHeldforSaleTotal { get; set; }
        public string HedgingAssetsNonCurrent { get; set; }
        public string HedgingAssetsCurrent { get; set; }
        public string ConvertibleLoansTotal { get; set; }
        public string BankLoansTotal { get; set; }
        public string OtherLoansTotal { get; set; }
        public string HedgingLiabilitiesNonCurrent { get; set; }
        public string HedgingLiabilitiesCurrent { get; set; }
        public string InsuranceFundsNonCurrent { get; set; }
        public string InsuranceFundsCurrent { get; set; }
        public string DebtTotal { get; set; }
        public string AssetsHeldForSaleCurrent { get; set; }
        public string AssetsHeldForSaleNonCurrent { get; set; }
        public string BiologicalAssets { get; set; }
        public string CashRestrictedOrPledged { get; set; }
        public string ConvertibleLoansNonCurrent { get; set; }
        public string FinancialOrDerivativeInvestmentCurrentLiabilities { get; set; }
        public string LoanAndLoanReceivables { get; set; }
        public string TradeAndOtherReceivablesNonCurrent { get; set; }
        public string DebtDueInYear1 { get; set; }
        public string DebtDueInYear2 { get; set; }
        public string DebtDueInYear5 { get; set; }
        public string DebtDueBeyond { get; set; }
        public string TotalDebtInMaturitySchedule { get; set; }
        public string FixedAssetsRevaluationReserve { get; set; }
        public string CurrentOtherFinancialLiabilities { get; set; }
        public string NonCurrentOtherFinancialLiabilities { get; set; }
        public string OtherFinancialLiabilities { get; set; }
        public string OtherCurrentBorrowings { get; set; }
        
        public string Symbol { get; set; }
        public int ID { get; set; }
    }

    public class BalanceSheetModel:APIBase
    {
        public MessageInfo MessageInfo { get; set; }
        public GeneralInfo GeneralInfo { get; set; }
        public List<BalanceSheetEntityList> BalanceSheetEntityList { get; set; }
    }
}
